# Nombre del flujo de trabajo que aparecerá en la pestaña "Actions" de GitHub
name: Deploy React App to GitHub Pages

# Configura cuándo se debe ejecutar este flujo de trabajo
on:
  # Se ejecuta en cada push a la rama 'main'
  push:
    branches: ["main"]
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Configura los permisos que necesitará el job para desplegar
permissions:
  contents: read
  pages: write
  id-token: write

# Un flujo de trabajo se compone de uno o más "jobs" que se ejecutan en secuencia o en paralelo
jobs:
  # Este job se encarga de construir la aplicación
  build:
    runs-on: ubuntu-latest # Se ejecutará en una máquina virtual de Ubuntu

    steps:
      # 1. Clona tu repositorio para tener acceso al código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura el entorno de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Puedes usar la versión de Node que prefieras
          cache: "npm" # Habilita el caché para acelerar futuras instalaciones

      # 3. Instala las dependencias del proyecto
      - name: Install dependencies
        run: npm ci # 'npm ci' es más rápido y seguro para entornos de automatización que 'npm install'

      # 4. Construye el proyecto para producción
      # El script 'build' debe generar los archivos en la carpeta 'dist' (o 'build')
      - name: Build project
        run: npm run build

      # 5. Sube los artefactos de la build para que el job de despliegue los use
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Sube el contenido de la carpeta 'dist'. Si tu proyecto construye en 'build', cámbialo.
          path: "./dist" 

  # Este job se encarga de desplegar la aplicación
  deploy:
    # El job de despliegue depende de que el job de 'build' haya terminado exitosamente
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # La URL del sitio desplegado

    steps:
      # Despliega los artefactos subidos a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
